apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-infra-1
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: charts
    repoURL: https://github.com/flamurdamoni/kubernetes
    targetRevision: main
    helm:
      valueFiles:
      - values-infra.yaml