apiVersion: v2
appVersion: 1.27.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: NGINX Open Source is a web server that can be also used as a reverse
  proxy, load balancer, and HTTP cache. Recommended for high-demanding sites due to
  its ability to provide faster content.

name: nginx
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/nginx
version: 18.2.5
