apps:
  cert-manager:
    namespace: cert-manager
    helmValues:
      cert-manager.replicaCount: "2"
  keycloak:
    namespace: auth
    helmValues:
      keycloak.replicaCount: "2"
  nginx:
    namespace: nginx
    helmValues:
      cert-manager.replicaCount: "2"
  nginx1:
    namespace: nginx1
    helmValues:
      cert-manager.replicaCount: "2"

  nginx2:
    namespace: nginx2
    helmValues:
      cert-manager.replicaCount: "2"